apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfooversikt
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /health/isAlive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /health/isReady
    initialDelay: 20
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /actuator/metrics
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      replyURLs:
        - "https://syfooversikt.dev.intern.nav.no/oauth2/callback"
      claims:
        extra:
          - "NAVident"
  envFrom:
    - secret: syfooversikt-session-key
  webproxy: true
  ingresses:
    - "https://syfooversikt.dev.intern.nav.no"
  env:
    - name: NODE_ENV
      value: 'production'
    - name: AUTH_REDIRECT_URI
      value: "https://syfooversikt.dev.intern.nav.no/oauth2/callback"
    - name: REDIS_HOST
      value: "syfooversikt-redis"
    - name: INTERNARBEIDSFLATEDECORATOR_HOST
      value: "internarbeidsflatedecorator-q0.dev.intern.nav.no"
    - name: SYFOOVERSIKTSRV_AAD_APP_CLIENT_ID
      value: "dev-fss.teamsykefravr.syfooversiktsrv"
    - name: SYFOPERSON_AAD_APP_CLIENT_ID
      value: "dev-fss.teamsykefravr.syfoperson"
    - name: SYFOVEILEDER_AAD_APP_CLIENT_ID
      value: "dev-gcp.teamsykefravr.syfoveileder"
    - name: MODIACONTEXTHOLDER_HOST
      value: "modiacontextholder-q0.dev.adeo.no"
    - name: SYFOOVERSIKTSRV_HOST
      value: "syfooversiktsrv.dev.intern.nav.no"
    - name: SYFOPERSON_HOST
      value: "syfoperson.dev.intern.nav.no"
    - name: SYFOVEILEDER_HOST
      value: "syfoveileder.dev.intern.nav.no"
