apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfooversikt
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /health/isAlive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /health/isReady
    initialDelay: 20
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /actuator/metrics
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  azure:
    sidecar:
      enabled: true
      autoLogin: true
    application:
      allowAllUsers: true
      enabled: true
      tenant: nav.no
      claims:
        extra:
          - "NAVident"
  valkey:
    - instance: cache
      access: readwrite
  envFrom:
    - secret: syfooversikt-session-key
    - secret: syfooversikt-unleash-api-token
  accessPolicy:
    outbound:
      external:
        - host: "login.microsoftonline.com"
        - host: "ereg-services.prod-fss-pub.nais.io"
        - host: "teamsykefravr-unleash-api.nav.cloud.nais.io"
      rules:
        - application: syfooversiktsrv
        - application: syfoperson
        - application: syfoveileder
        - application: flexjar-backend
          namespace: flex
        - application: modiacontextholder
          namespace: personoversikt
  ingresses:
    - "https://syfooversikt.intern.nav.no"
  env:
    - name: NAIS_CONTEXT
      value: "prod"
    - name: NODE_ENV
      value: 'production'
    - name: AUTH_REDIRECT_URI
      value: "https://syfooversikt.intern.nav.no/oauth2/callback"
    - name: EREG_HOST
      value: "https://ereg-services.prod-fss-pub.nais.io"
    - name: SYFOOVERSIKTSRV_AAD_APP_CLIENT_ID
      value: "prod-gcp.teamsykefravr.syfooversiktsrv"
    - name: SYFOPERSON_AAD_APP_CLIENT_ID
      value: "prod-gcp.teamsykefravr.syfoperson"
    - name: SYFOVEILEDER_AAD_APP_CLIENT_ID
      value: "prod-gcp.teamsykefravr.syfoveileder"
    - name: MODIACONTEXTHOLDER_AAD_APP_CLIENT_ID
      value: "prod-gcp.personoversikt.modiacontextholder"
    - name: MODIACONTEXTHOLDER_HOST
      value: "http://modiacontextholder.personoversikt"
    - name: SYFOOVERSIKTSRV_HOST
      value: "http://syfooversiktsrv"
    - name: SYFOPERSON_HOST
      value: "http://syfoperson"
    - name: SYFOVEILEDER_HOST
      value: "http://syfoveileder"
    - name: FLEXJAR_AAD_APP_CLIENT_ID
      value: "prod-gcp.flex.flexjar-backend"
    - name: FLEXJAR_HOST
      value: "http://flexjar-backend.flex"
