apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfooversikt
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /health/isAlive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /health/isReady
    initialDelay: 20
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /actuator/metrics
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  azure:
    sidecar:
      enabled: true
      autoLogin: true
    application:
      allowAllUsers: true
      enabled: true
      tenant: trygdeetaten.no
      claims:
        extra:
          - "NAVident"
  envFrom:
    - secret: syfooversikt-session-key
    - secret: syfooversikt-redis-password
    - secret: syfooversikt-unleash-api-token
  accessPolicy:
    outbound:
      external:
        - host: "login.microsoftonline.com"
        - host: "internarbeidsflatedecorator-q1.dev-fss-pub.nais.io"
        - host: "modiacontextholder-q1.dev-fss-pub.nais.io"
        - host: "ereg-services-q1.dev-fss-pub.nais.io"
        - host: "teamsykefravr-unleash-api.nav.cloud.nais.io"
      rules:
        - application: syfooversiktsrv
        - application: syfoperson
        - application: syfoveileder
        - application: syfooversikt-redis
  ingresses:
    - "https://syfooversikt.intern.dev.nav.no"
  env:
    - name: NAIS_CONTEXT
      value: "dev"
    - name: NODE_ENV
      value: 'production'
    - name: AUTH_REDIRECT_URI
      value: "https://syfooversikt.intern.dev.nav.no/oauth2/callback"
    - name: REDIS_HOST
      value: "syfooversikt-redis"
    - name: EREG_HOST
      value: "https://ereg-services-q1.dev-fss-pub.nais.io"
    - name: INTERNARBEIDSFLATEDECORATOR_HOST
      value: "https://internarbeidsflatedecorator-q1.dev-fss-pub.nais.io"
    - name: SYFOOVERSIKTSRV_AAD_APP_CLIENT_ID
      value: "dev-gcp.teamsykefravr.syfooversiktsrv"
    - name: SYFOPERSON_AAD_APP_CLIENT_ID
      value: "dev-gcp.teamsykefravr.syfoperson"
    - name: SYFOVEILEDER_AAD_APP_CLIENT_ID
      value: "dev-gcp.teamsykefravr.syfoveileder"
    - name: MODIACONTEXTHOLDER_AAD_APP_CLIENT_ID
      value: "dev-fss.personoversikt.modiacontextholder-q1"
    - name: MODIACONTEXTHOLDER_HOST
      value: "https://modiacontextholder-q1.dev-fss-pub.nais.io"
    - name: SYFOOVERSIKTSRV_HOST
      value: "http://syfooversiktsrv"
    - name: SYFOPERSON_HOST
      value: "http://syfoperson"
    - name: SYFOVEILEDER_HOST
      value: "http://syfoveileder"
