export enum HendelseType {
  AKTIVITETSKRAV,
  ARBEIDSUFORHET,
  BISTANDSBEHOV_FRA_BEHANDLER,
  DIALOGMELDING,
  DIALOGMOTE,
  DIALOGMOTE_MOTEBEHOV,
  DIALOGMOTE_NYTT_SVAR,
  FRISKMELDING_TIL_ARBEIDSFORMIDLING,
  OPPFOLGINGSOPPGAVE,
  OPPFOLGINGSPLAN,
  SEN_OPPFOLGING,
  MANGLENDE_MEDVIRKNING,
  KARTLEGGINGSSPORSMAL,
}

export interface Hendelse {
  type: HendelseType;
  text: string;
}
