apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: teamsykefravr
  annotations:
    nais.io/read-only-file-system: "false"
    nais.io/run-as-user: "999"
  name: syfooversikt-redis
  namespace: teamsykefravr
spec:
  image: redis:5-alpine
  port: 6379
  replicas: # A single Redis-app doesn't scale
    min: 1
    max: 1 # More replicas doesn't sync
  resources: # you need to monitor the resource usage yourself
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 200m
      memory: 128Mi
  service:
    port: 6379
    protocol: redis
  accessPolicy:
    inbound:
      rules:
        - application: syfooversikt
