name: main

on: push

jobs:
  build-and-deploy:
    uses: navikt/isworkflows/.github/workflows/node-build-deploy.yml@master
    with:
      dev-cluster: dev-gcp
      prod-cluster: prod-gcp
      node-version: 18
      distroless: true
    secrets: inherit
