name: main

on: push

jobs:
  build-and-deploy:
    permissions:
      packages: read
      contents: read
      id-token: write
    uses: navikt/isworkflows/.github/workflows/node-build-deploy-pnpm.yml@master
    with:
      node-version: 22
    secrets: inherit
