name: Pull request

on: [pull_request]

jobs:
  build-push-deploy:
    name: Checkout code and create docker tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install deps
        run: |
          npm install
      - name: Run tests
        run: |
          npm run test
      - name: Build
        run: |
          npm run nais-build
